### ISSUE TITLE
App crash on screen rotate while getting file list

### ISSUE THREAD

**Issue by foofoodog** [mariogrip/octodroid#14]
Rotating the screen while in the process of getting the file list kills the app 100% of the time on a Moto G 1st gen running lollipop.

**Comment by mariogrip** [comment]
Thanks for reporting, I will try to push a new version today that fixes this.

Best regards, 
Marius

**Comment by mariogrip** [comment]
I uploaded a new version just now, you should get an update on your device soon (1-12 Hours). 

If this not fix your issue, Please let me know. 

Thanks for reporting!
